[package]
name = "dissect"
version = "0.2.0"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"
description = "Logstash inspired dissect extractor"
readme = "README.md"

[dependencies]
halfbrown = "0.1"
simd-json = {version = "0.4", features = ["known-key"]}
