[package]
name = "dissect"
version = "0.6.0"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"
description = "Logstash inspired dissect extractor"
readme = "README.md"

[dependencies]
simd-json = { version = "0.10", features = ["known-key"] }
