name: Checks

on: [push, pull_request]

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check license headers
        run: ./.github/checks/copyright.sh
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Safety checks
        run: ./.github/checks/safety.sh -a
  unused-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo snap install remarshal
      - name: Install deps
        run: sudo snap install --classic ripgrep
      - uses: actions/checkout@v4
      - name: Check for unused dependencies
        run: ./.github/checks/deps.sh .
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: stable
      - name: Check Formating
        run: cargo fmt --all -- --check
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: stable
      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy action to produce annotations
        uses: actions-rs/clippy-check@v1
        if: steps.check_permissions.outputs.has-permission
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all
      - name: Run clippy manually without annotations
        if: ${{ !steps.check_permissions.outputs.has-permission }}
        run: cargo clippy --all
