name: Tests

on: [push, pull_request]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: llvm-tools-preview
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        env:
          RUSTFLAGS: -D warnings -C target-cpu=native
          RUST_BACKTRACE: 1
        run: cargo llvm-cov --workspace --lcov --output-path lcov.txt
      - uses: codecov/codecov-action@v5
        with:
          files: ./lcov.txt # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)   
